// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 9,
                            Name = "Rose",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            Name = "Cannoli",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 8,
                            Name = "Blue",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 7,
                            Name = "Finley",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 8,
                            Name = "Ludovica",
                            Type = "cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
